import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'


import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.index}>
      <Head>
        <title>Portifolio Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.color}>Home</h1>

      <Link href="/about">
        <a>About</a>
      </Link>
      
    </div>
  )
}

export default Home
