import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Header from '../components/Header/Header';
// import Link from 'next/link'

import MainPage from './MainPage/MainPage';
import About from './About/About';
import Skills from './Skills/Skills';
import Contact from './Contact/Contact';
import Projects from './Projects/Projects';

const Home: NextPage = () => {
  return (
    <div className={styles.home}>
      <Head>
        <title>Portifolio Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.home_main}>
        <Header/>
        <MainPage/>
        <About/>
        <Skills/>
        <Projects/>
        <Contact/>
      </div>
    </div>
  )
}

export default Home
